# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OGallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OGallery
  pod 'Alamofire'
  
  target 'OGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OGalleryUITests' do
    # Pods for testing
  end

end
